apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
    containers: 
      - name: kubectl
        image: joshendriks/alpine-k8s
        command:
          - /bin/cat
        tty: true
      - name: docker
        image: docker
        args: ["sleep", "10000"]
        volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
    volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
